"""
registration node — LLM agent.

Generates the patching logic that swaps original modules for FlatQuant
quantized ones: apply_flatquant_to_{model} and a runner script.
"""

import ast
import json
import re
import time
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage
from llm import anthropic_text, get_codegen_llm
from prompts import REGISTRATION_PROMPT
from state import AgentState


def _model_slug(model_name: str) -> str:
    base = model_name.split("/")[-1]
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", base).lower().strip("_")
    return slug


def registration_node(state: AgentState) -> dict[str, Any]:
    """
    LangGraph node: generate module patching / registration code.

    Appends to generated_files and sets registration_code.
    """
    model_name: str = state["model_name"]
    slug = _model_slug(model_name)
    model_type: str = state.get("model_type", "unknown")
    model_config: dict = state.get("model_config", {})
    linears: dict = state.get("linears", {})
    ref_patterns: dict = state.get("ref_patterns", {})
    generated_files: dict = state.get("generated_files", {})

    print(f"[registration] Generating patching logic for {model_name} ...", flush=True)

    # Summarise linears (same deduplicated format as codegen uses).
    linears_summary = _summarise_linears(linears)

    utils_key = f"{slug}_utils.py"
    utils_src = generated_files.get(utils_key, "")
    codegen_class_names = _extract_flatquant_class_names(utils_src)

    quant_key = f"quant_config_{slug}.py"
    quant_src = generated_files.get(quant_key, "")
    quant_config_functions = _extract_module_level_function_names(quant_src)

    user_message = (
        f"model_name: {model_name}\n"
        f"slug: {slug}\n"
        f"model_type: {model_type}\n\n"
        f"codegen_class_names (exact FlatQuant wrapper classes in {utils_key} — use ONLY these in imports):\n"
        f"{json.dumps(codegen_class_names, indent=2)}\n\n"
        f"quant_config_top_level_functions (from {quant_key} — import only these names from quant_config):\n"
        f"{json.dumps(quant_config_functions, indent=2)}\n\n"
        f"model_config (selected):\n"
        f"{json.dumps(_selected_config(model_config), indent=2)}\n\n"
        f"linears (deduplicated):\n"
        f"{json.dumps(linears_summary, indent=2)}\n\n"
        f"ref_patterns:\n"
        f"{json.dumps(ref_patterns, indent=2)}\n\n"
        f"Files already generated by codegen (filenames only):\n"
        f"{json.dumps(list(generated_files.keys()), indent=2)}\n\n"
        "Generate patch_{slug}.py and run_{slug}.py as a JSON object {{filename: source_code}}."
    )

    llm = get_codegen_llm()

    messages = [
        SystemMessage(content=REGISTRATION_PROMPT),
        HumanMessage(content=user_message),
    ]

    print(
        "[registration] Calling codegen LLM (Anthropic); no further logs until the response returns "
        "(often ~1-6+ minutes).",
        flush=True,
    )
    t0 = time.perf_counter()
    response = llm.invoke(messages)
    print(f"[registration] LLM round-trip took {time.perf_counter() - t0:.1f}s", flush=True)
    raw_text: str = anthropic_text(response)

    new_files = _parse_json_response(raw_text)

    # Merge registration files into generated_files.
    merged = {**generated_files, **new_files}

    # Expose the patching function source separately for easy access.
    patch_key = next((k for k in new_files if k.startswith("patch_")), None)
    registration_code = new_files.get(patch_key, "") if patch_key else ""

    print(f"[registration] Generated registration files: {list(new_files.keys())}", flush=True)

    return {
        "generated_files": merged,
        "registration_code": registration_code,
        "messages": state.get("messages", []) + [
            {
                "role": "assistant",
                "content": f"[registration_node] Generated: {list(new_files.keys())}",
            }
        ],
    }


def _extract_module_level_function_names(source: str) -> list[str]:
    """Top-level def names in a module (AST)."""
    if not source:
        return []
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    return sorted(
        n.name
        for n in tree.body
        if isinstance(n, ast.FunctionDef)
    )


def _extract_flatquant_class_names(source: str) -> list[str]:
    """Class names starting with FlatQuant from generated utils (AST)."""
    if not source:
        return []
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    names: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name.startswith("FlatQuant"):
            names.append(node.name)
    return sorted(set(names))


def _selected_config(config: dict) -> dict:
    keys = [
        "model_type", "hidden_size", "num_hidden_layers",
        "num_attention_heads", "num_key_value_heads",
    ]
    return {k: config[k] for k in keys if k in config}


def _summarise_linears(linears: dict) -> dict:
    seen: dict[str, str] = {}
    for name, shape in linears.items():
        pattern = re.sub(r"\.\d+\.", ".N.", name)
        if pattern not in seen:
            seen[pattern] = f"{shape['in_features']} → {shape['out_features']}"
    return seen


def _parse_json_response(raw_text: str) -> dict:
    text = raw_text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-z]*\n?", "", text)
        text = re.sub(r"\n?```$", "", text.strip())
    try:
        result = json.loads(text)
        if isinstance(result, dict):
            return result
    except json.JSONDecodeError:
        pass

    files = {}
    pattern = r"###?\s*`?([^`\n]+\.py)`?\s*\n```python\n(.*?)```"
    for match in re.finditer(pattern, raw_text, re.DOTALL):
        filename = match.group(1).strip()
        code = match.group(2).strip()
        files[filename] = code

    if files:
        return files

    return {"_raw_registration_output.txt": raw_text}
